server:
  port: 8004
# 应用名称
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: fc-async

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fc_async?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: Wadxq19960303
    filters: config
    connectionProperties: config.decrypt=true;config.decrypt.key=yyy

  resources:
    add-mappings: true
    static-locations: classpath:/static/

  kafka:
    bootstrap-servers: localhost:9092  # Kafka集群地址，多个地址用逗号分隔
    producer:
      # 键的序列化方式
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 值的序列化方式（建议使用Json，这种序列化方式可以无需额外配置传输实体类）
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # 值的反序列化方式（建议使用Json，这种序列化方式可以无需额外配置传输实体类）
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: jcq-group  # 消费者组ID
      auto-offset-reset: earliest  # 默认起始偏移量
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        max-poll-records: 500  # 每次拉取的最大记录数
        enable-auto-commit: false  # 是否自动提交偏移量
#    listener:
#      auto-startup: true  # 是否自动启动监听器
#      concurrency: 3  # 消费者线程数
#      batch-listener: true  # 是否启用批量监听
#      ack-mode: record  # 确认模式，默认记录级别确认
#      max-attempts: 10  # 最大重试次数

# 以下配置都有默认值
# 核心线程数
async:
  enabled: true
  executor:
    thread:
      corePoolSize: 10
      maxPoolSize: 50
      queueCapacity: 10000
      keepAliveSeconds: 600
  # 自定义队列名称前缀：默认应用名称
  topic: ${spring.application.name}
  # 重试执行次数：默认5次
  exec:
    # 执行成功是否删除记录：默认删除
    deleted: true
    count: 5
  # 重试最大查询数量
  retry:
    limit: 100
  # 补偿最大查询数量
  comp:
    limit: 100
  # 登录拦截：默认false
  login: false